"""
Iterative DiffusionDPO alignment loop.

Problem with standard DPO: the preference dataset was collected from the
initial LoRA model. As the policy updates, the dataset becomes stale —
preferences between videos generated by the old policy may not reflect
improvements we want to reinforce in the new policy.

Solution: alternate between generation and DPO update cycles, similar to
iterative_dpo.py in rlhf-and-reward-modelling-alt (Notebook 14).

Each iteration:
  1. Generate N video pairs per prompt using the current policy.
  2. Score pairs with the reward model → label (chosen, rejected).
  3. Run K DPO gradient steps on fresh on-policy pairs.
  4. Evaluate win rate on held-out prompts vs. the initial LoRA baseline.
  5. Append pairs to rolling buffer (size depends on buffer strategy).
  6. Repeat until max_iterations or win_rate >= target.

Buffer strategies (same as iterative_dpo.py in prior repo):
  "current":  only this iteration's pairs (lowest variance, noisiest).
  "rolling2": last 2 iterations' pairs (balanced).
  "full":     all historical pairs (highest signal, distribution mismatch risk).
"""

from __future__ import annotations

import json
import os
from collections import deque
from typing import Deque, Dict, List, Optional

import torch
from tqdm import tqdm

from ..data.preference_dataset import VideoPreferenceDataset, save_preference_jsonl, load_preference_jsonl
from ..data.video_metrics import compute_video_metrics
from ..models.lora_adapter import CogVideoXLoRA
from ..models.video_reward_model import VideoRewardModel
from .dpo_video import DiffusionDPOTrainer, diffusion_elbo


class IterativeDPOLoop:
    """
    Runs the iterative DiffusionDPO alignment loop.

    Args:
        config: dict loaded from iterative_dpo_config.yaml.
    """

    def __init__(self, config: dict):
        self.config = config
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def setup(self):
        cfg = self.config
        model_cfg = cfg["model"]

        dtype_map = {"bfloat16": torch.bfloat16, "float16": torch.float16, "float32": torch.float32}
        dtype = dtype_map[model_cfg.get("dtype", "bfloat16")]

        # Current policy (updated each iteration)
        print("Loading initial policy...")
        self.policy = CogVideoXLoRA.from_lora_checkpoint(
            base_model=model_cfg["pretrained_model_name_or_path"],
            lora_checkpoint=model_cfg["lora_checkpoint"],
            dtype=dtype,
            device=str(self.device),
        )

        # Frozen baseline (for win rate comparison)
        print("Loading baseline policy (frozen)...")
        self.baseline = CogVideoXLoRA.from_lora_checkpoint(
            base_model=model_cfg["pretrained_model_name_or_path"],
            lora_checkpoint=model_cfg["lora_checkpoint"],
            dtype=dtype,
            device=str(self.device),
        )
        for p in self.baseline.transformer.parameters():
            p.requires_grad_(False)

        # Reward model
        print("Loading reward model...")
        self.reward_model = VideoRewardModel().to(self.device)
        self.reward_model.load_state_dict(
            torch.load(model_cfg["reward_model_checkpoint"], map_location=self.device)
        )
        self.reward_model.eval()

        gen_cfg = cfg["generation"]
        with open(gen_cfg["prompts_path"]) as f:
            self.train_prompts = [l.strip() for l in f if l.strip()]
        with open(gen_cfg["eval_prompts_path"]) as f:
            self.eval_prompts = [l.strip() for l in f if l.strip()]

        self.base_dir = cfg["output"]["base_dir"]
        os.makedirs(self.base_dir, exist_ok=True)

        # Buffer management
        buffer_strategy = cfg["buffer"]["strategy"]
        if buffer_strategy == "current":
            self._buffer_maxlen = 1
        elif buffer_strategy == "rolling2":
            self._buffer_maxlen = 2
        else:  # "full"
            self._buffer_maxlen = None  # unlimited

        self._iteration_records: Deque[List] = deque(maxlen=self._buffer_maxlen)
        self._all_history: List[Dict] = []

    def _generate_video(self, prompt: str, out_path: str, gen_cfg: dict) -> None:
        """Generate a single video and save to out_path."""
        if os.path.exists(out_path):
            return
        import imageio
        result = self.policy.pipe(
            prompt=prompt,
            num_frames=gen_cfg.get("num_frames", 16),
            height=gen_cfg.get("height", 480),
            width=gen_cfg.get("width", 720),
            num_inference_steps=gen_cfg.get("num_inference_steps", 50),
            guidance_scale=gen_cfg.get("guidance_scale", 6.0),
        )
        imageio.mimsave(out_path, result.frames[0], fps=8, codec="libx264")

    def _rollout(self, iteration: int) -> List[Dict]:
        """
        Generate video pairs and score with reward model.
        Returns a list of preference records.
        """
        gen_cfg = self.config["generation"]
        iter_dir = os.path.join(self.base_dir, f"iter_{iteration:02d}", "videos")
        os.makedirs(iter_dir, exist_ok=True)

        records = []
        data_cfg = self.config.get("data_generation", {})
        num_frames = gen_cfg.get("num_frames", 16)
        height = gen_cfg.get("height", 480)
        width = gen_cfg.get("width", 720)
        min_gap = data_cfg.get("min_score_gap", 0.03)

        print(f"\n  Generating rollouts for iteration {iteration}...")
        for i, prompt in enumerate(tqdm(self.train_prompts, desc="Rollout")):
            path_a = os.path.join(iter_dir, f"{i:04d}_A.mp4")
            path_b = os.path.join(iter_dir, f"{i:04d}_B.mp4")

            self._generate_video(prompt, path_a, gen_cfg)
            self._generate_video(prompt, path_b, gen_cfg)

            # Score with reward model
            from ..data.video_dataset import load_video_frames
            frames_a = load_video_frames(path_a, num_frames, height, width)
            frames_b = load_video_frames(path_b, num_frames, height, width)

            with torch.no_grad():
                out_a = self.reward_model(frames_a.unsqueeze(0).to(self.device))
                out_b = self.reward_model(frames_b.unsqueeze(0).to(self.device))

            score_a = out_a.rewards.item()
            score_b = out_b.rewards.item()
            gap = abs(score_a - score_b)

            if gap < min_gap:
                continue  # too close to call — skip noisy pairs

            chosen, rejected = (path_a, path_b) if score_a >= score_b else (path_b, path_a)
            score_c = max(score_a, score_b)
            score_r = min(score_a, score_b)

            records.append({
                "prompt": prompt,
                "chosen": chosen,
                "rejected": rejected,
                "source": f"iter_{iteration}",
                "scores": {"chosen": round(score_c, 4), "rejected": round(score_r, 4)},
            })

        print(f"  Generated {len(records)} preference pairs (iteration {iteration})")
        return records

    def _get_buffer_records(self, new_records: List[Dict]) -> List[Dict]:
        """Combine new records with rolling buffer based on strategy."""
        self._iteration_records.append(new_records)
        all_records = []
        for batch in self._iteration_records:
            all_records.extend(batch)
        return all_records

    def _dpo_update(self, records: List[Dict], iteration: int) -> None:
        """Run K DPO gradient steps on the given preference records."""
        iter_dir = os.path.join(self.base_dir, f"iter_{iteration:02d}")
        prefs_path = os.path.join(iter_dir, "preferences.jsonl")
        save_preference_jsonl(records, prefs_path)

        dpo_cfg_base = self.config["dpo"]
        iter_output = os.path.join(iter_dir, "dpo_checkpoint")

        # Build a minimal DPO config for this iteration
        dpo_config = {
            "model": {
                "pretrained_model_name_or_path": self.config["model"]["pretrained_model_name_or_path"],
                "lora_checkpoint": self._last_checkpoint_path,
                "dtype": self.config["model"].get("dtype", "bfloat16"),
            },
            "lora": self.config.get("lora_config", {
                "r": 16, "alpha": 32,
                "target_modules": ["to_q", "to_k", "to_v", "to_out.0", "ff.net.0.proj", "ff.net.2"],
                "bias": "none",
            }),
            "dpo": {
                "beta": dpo_cfg_base["beta"],
                "num_timesteps": dpo_cfg_base.get("num_timesteps", 50),
                "label_smoothing": dpo_cfg_base.get("label_smoothing", 0.0),
            },
            "data": {
                "preference_path": prefs_path,
                "num_frames": self.config["generation"].get("num_frames", 16),
                "height": self.config["generation"].get("height", 480),
                "width": self.config["generation"].get("width", 720),
                "train_split": 0.9,
            },
            "training": {
                "output_dir": iter_output,
                "num_epochs": 1,
                "batch_size": dpo_cfg_base.get("batch_size", 1),
                "gradient_accumulation_steps": dpo_cfg_base.get("gradient_accumulation_steps", 4),
                "learning_rate": dpo_cfg_base["learning_rate"],
                "lr_warmup_steps": 10,
                "max_grad_norm": 1.0,
                "mixed_precision": "bf16",
                "logging_steps": 50,
                "save_steps": dpo_cfg_base.get("num_grad_steps", 200) + 1,  # only save at end
            },
        }

        trainer = DiffusionDPOTrainer(dpo_config)
        trainer.setup()
        final_path = trainer.train()
        self._last_checkpoint_path = final_path

        # Reload policy from updated checkpoint
        self.policy = CogVideoXLoRA.from_lora_checkpoint(
            base_model=self.config["model"]["pretrained_model_name_or_path"],
            lora_checkpoint=final_path,
            dtype=torch.bfloat16,
            device=str(self.device),
        )

    def _evaluate_win_rate(self, iteration: int) -> float:
        """
        Compute win rate: fraction of eval prompts where the current policy
        generates a higher-reward video than the baseline.
        """
        gen_cfg = self.config["generation"]
        num_eval = self.config["evaluation"].get("num_eval_prompts", 20)
        eval_prompts = self.eval_prompts[:num_eval]

        num_frames = gen_cfg.get("num_frames", 16)
        height = gen_cfg.get("height", 480)
        width = gen_cfg.get("width", 720)
        eval_dir = os.path.join(self.base_dir, f"iter_{iteration:02d}", "eval")
        os.makedirs(eval_dir, exist_ok=True)

        wins = 0
        from ..data.video_dataset import load_video_frames
        import imageio

        for i, prompt in enumerate(tqdm(eval_prompts, desc="Eval")):
            policy_path = os.path.join(eval_dir, f"{i:03d}_policy.mp4")
            baseline_path = os.path.join(eval_dir, f"{i:03d}_baseline.mp4")

            # Generate with current policy
            self._generate_video(prompt, policy_path, gen_cfg)

            # Generate with baseline
            if not os.path.exists(baseline_path):
                result = self.baseline.pipe(
                    prompt=prompt,
                    num_frames=num_frames, height=height, width=width,
                    num_inference_steps=gen_cfg.get("num_inference_steps", 50),
                    guidance_scale=gen_cfg.get("guidance_scale", 6.0),
                )
                imageio.mimsave(baseline_path, result.frames[0], fps=8, codec="libx264")

            frames_p = load_video_frames(policy_path, num_frames, height, width)
            frames_b = load_video_frames(baseline_path, num_frames, height, width)

            with torch.no_grad():
                score_p = self.reward_model(frames_p.unsqueeze(0).to(self.device)).rewards.item()
                score_b = self.reward_model(frames_b.unsqueeze(0).to(self.device)).rewards.item()

            if score_p > score_b:
                wins += 1

        win_rate = wins / len(eval_prompts)
        print(f"  Win rate (iteration {iteration}): {win_rate:.3f} ({wins}/{len(eval_prompts)})")
        return win_rate

    def run(self):
        """Main iterative loop."""
        cfg = self.config
        max_iterations = cfg["loop"]["max_iterations"]
        target_win_rate = cfg["loop"]["target_win_rate"]
        eval_every = cfg["evaluation"].get("eval_every_n_iterations", 1)

        self._last_checkpoint_path = self.config["model"]["lora_checkpoint"]

        history = []
        for iteration in range(1, max_iterations + 1):
            print(f"\n{'='*60}")
            print(f"ITERATION {iteration}/{max_iterations}")
            print(f"{'='*60}")

            # 1. Generate on-policy preference pairs
            new_records = self._rollout(iteration)
            self._all_history.extend(new_records)

            # 2. Build buffer
            buffer_records = self._get_buffer_records(new_records)
            print(f"  Buffer size: {len(buffer_records)} pairs")

            # 3. DPO update
            self._dpo_update(buffer_records, iteration)

            # 4. Evaluate
            win_rate = None
            if iteration % eval_every == 0:
                win_rate = self._evaluate_win_rate(iteration)
                history.append({"iteration": iteration, "win_rate": win_rate, "n_pairs": len(buffer_records)})

                # Save history
                with open(os.path.join(self.base_dir, "history.json"), "w") as f:
                    json.dump(history, f, indent=2)

                if win_rate >= target_win_rate:
                    print(f"\nTarget win rate {target_win_rate:.2f} reached! Stopping.")
                    break

        print(f"\nIterative DPO complete. Final checkpoint: {self._last_checkpoint_path}")
        print(f"Win rate history: {[f'{h[\"win_rate\"]:.3f}' for h in history]}")
        return self._last_checkpoint_path, history
